### ISSUE TITLE
فایل ایراد دارد 

### ISSUE THREAD

**Issue by mohammadali135456** [Vigiatonet/Vigiland#4]
با سلام 

این فایل مپ ویجیلند ایراد دارد و کامل نیست و ناقص است لطفا فایل درست و کامل را برای استفاده همه اپلود کنید ممنون

**Comment by shirin-manzari** [comment]
سلام فایل برای به حجم کم رسیده شدن trim شده و فقط محدوده‌ی شهر رو شامل میشه. اگه بگی چه مشکلی داری کمکت می‌کنم.

**Comment by mohammadali135456** [comment]
سلام زمانی که فایل رو اکستر می کنم و فایل مپ رو تو پوشه سیو می ندازم و می رم تو گیم مپ رو تو سیو من نشون نمی ده و این به نظرم مشکل فایل شاید باشه حالا بازم ممنون می شم راهنمایی کنید
